version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: aura-mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - aura-network

  bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: aura-bot
    restart: unless-stopped
    depends_on:
      - mongodb
    env_file:
      - .env
    environment:
      MONGODB_URI: mongodb://admin:password123@mongodb:27017/aura-bot?authSource=admin
    networks:
      - aura-network

  dashboard:
    build:
      context: .
      dockerfile: Dockerfile.dashboard
    container_name: aura-dashboard
    restart: unless-stopped
    depends_on:
      - mongodb
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      MONGODB_URI: mongodb://admin:password123@mongodb:27017/aura-bot?authSource=admin
      DASHBOARD_PORT: 3000
    networks:
      - aura-network

volumes:
  mongodb_data:

networks:
  aura-network:
    driver: bridge
